### ISSUE TITLE
Create user profile UI

### ISSUE THREAD

**Issue by michaeldimimu** [MecuriiTech/vicsmall-fe#11]

**Comment by Abas-dev** [comment]
@michael-salam if you have finished with the issue, close it when the PR is merged 

check how to do it.

**Comment by michael-salam** [comment]
Yeah, I just finished it now, actually

**Comment by michaeldimimu** [comment]
> @michael-salam if you have finished with the issue, close it when the PR is merged 
> 
> check how to do it. 
> 

Yeah I just finished the ui now, actually 

Had to do some responsiveness edits

I'll close the issue now
